#!/usr/bin/env ruby

# frozen_string_literal: true

require 'os'
require 'docx'
require 'yaml'

vars = YAML.safe_load(File.read('variables.yml'))

begin
  document = Docx::Document.open('cover_letter_template.docx')
rescue StandardError => e
  print "Unable to open file. Error: #{e.message}"
  exit(1)
end

print "\nRunning validations..."
raise 'Empty value found in hash. Please fill all values and try again' if vars.values.any?(&:empty?)

print "\nRunning substitutions..."
document.paragraphs.each do |p|
  p.each_text_run do |tr|
    vars.each_key { |key| tr.substitute("{{#{key}}}", vars[key]) }
  end
end

file_name = if vars['CANDIDATE_NAME'].nil? || vars['JOB_COMPANY'].nil?
              "CL_#{rand(1000)}.docx"
            else
              "#{vars['CANDIDATE_NAME'].upcase.gsub(' ', '_')}_CL_#{vars['JOB_COMPANY'].split.first}.docx"
            end

document.save(file_name)
print "\nDone. Opening file #{file_name} ..."

if OS.mac?
  `open #{file_name} 2> /dev/null`
elsif OS.windows?
  `#{file_name}`
elsif OS.linux?
  `xdg-open #{file_name} 2> /dev/null`
end
